# Generated by Django 2.0.2 on 2018-02-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='azienda',
            options={'verbose_name_plural': 'Aziende'},
        ),
        migrations.AlterField(
            model_name='azienda',
            name='codice',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
