# Generated by Django 2.0.2 on 2018-02-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180222_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='codice_nullable',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
