# Generated by Django 2.0.2 on 2018-02-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_azienda_codice_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azienda',
            name='codice_nullable',
            field=models.CharField(default='12345', max_length=200),
        ),
    ]
