# Generated by Django 2.0.2 on 2018-02-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20180222_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azienda',
            name='codice_nullable',
        ),
    ]
