# Generated by Django 2.0.2 on 2018-02-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_azienda_codice_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='azienda',
            options={'ordering': ['nome', 'codice'], 'verbose_name_plural': 'Aziende'},
        ),
    ]
