# Generated by Django 2.0.2 on 2018-02-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_azienda_categoria_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
