# Generated by Django 2.0.2 on 2018-02-22 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_azienda_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cognome', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cf', models.CharField(blank=True, max_length=30, null=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persone', to='base.Azienda')),
            ],
            options={
                'verbose_name_plural': 'Persone',
                'ordering': ['cognome', 'nome'],
            },
        ),
    ]
