# Generated by Django 2.0.2 on 2018-02-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=30)),
                ('indirizzo', models.CharField(blank=True, max_length=200, null=True)),
                ('citta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Città')),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedi', to='base.Azienda')),
            ],
        ),
    ]
