# Generated by Django 2.0.2 on 2018-02-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='sedi',
            field=models.ManyToManyField(blank=True, related_name='sedi', to='base.Sede'),
        ),
    ]
